### ISSUE TITLE
md- prefix conflicts with ember-paper

### ISSUE THREAD

**Issue by nightexcessive** [johnotander/ember-cli-material-design-icons#5]
Hi,

I just wanted to let you know that the md- prefix that you use conflicts with https://github.com/miguelcobain/ember-paper 's md- prefix. Currently, it causes quite a few font issues. I fixed it on my local copy by doing a simple search & replace of `md-` to `mdi-`.

**Comment by johnotander** [comment]
Hey, thanks for taking the time to let me know!

I need to update [the icons](http://zavoloklom.github.io/material-design-iconic-font/) anyway, so when I do I'll be sure to change the prefix from `md-` to `mdi-`.

**Comment by nightexcessive** [comment]
Thanks! And by the way, thanks for maintaining this icon pack. :+1:

**Comment by johnotander** [comment]
@zavoloklom did the hard part of creating the icons. All I have to do is keep the `ember-cli` wrapper up to date. :sunglasses:

**Comment by johnotander** [comment]
I should be able to push out an update this evening or tomorrow, I'll keep you posted.

**Comment by johnotander** [comment]
Published to npm as `ember-cli-material-design-icons@0.4.0`.

**Comment by nightexcessive** [comment]
Awesome. Thanks again!

**Comment by johnotander** [comment]
: )
